// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs85UCTwCxponnOWVwVdaRfoIPm8c-9S4',
    appId: '1:364150503455:web:3b28ae3945b7c7578bfd2a',
    messagingSenderId: '364150503455',
    projectId: 'moneycentral-42aa3',
    authDomain: 'moneycentral-42aa3.firebaseapp.com',
    databaseURL: 'https://moneycentral-42aa3.firebaseio.com',
    storageBucket: 'moneycentral-42aa3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp6Yso1tzE2f3Wh5-BimP_UQu2amV6CDM',
    appId: '1:364150503455:android:73cf523332f57f5e',
    messagingSenderId: '364150503455',
    projectId: 'moneycentral-42aa3',
    databaseURL: 'https://moneycentral-42aa3.firebaseio.com',
    storageBucket: 'moneycentral-42aa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Flt5ae7EH5flrilMRAnto8koVJHOuAI',
    appId: '1:364150503455:ios:edf590ef10265c9c8bfd2a',
    messagingSenderId: '364150503455',
    projectId: 'moneycentral-42aa3',
    databaseURL: 'https://moneycentral-42aa3.firebaseio.com',
    storageBucket: 'moneycentral-42aa3.appspot.com',
    iosBundleId: 'com.luvyn.awesomeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Flt5ae7EH5flrilMRAnto8koVJHOuAI',
    appId: '1:364150503455:ios:96e2b1668c21d5968bfd2a',
    messagingSenderId: '364150503455',
    projectId: 'moneycentral-42aa3',
    databaseURL: 'https://moneycentral-42aa3.firebaseio.com',
    storageBucket: 'moneycentral-42aa3.appspot.com',
    iosBundleId: 'com.luvyn.awesomeapp.RunnerTests',
  );
}
